# Generated by Django 4.1.7 on 2023-03-21 00:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plantes', '0002_delete_historyplante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(max_length=30)),
                ('resume', models.TextField(max_length=500)),
                ('exposition', models.CharField(max_length=50)),
                ('entretien', models.CharField(max_length=10)),
                ('arrosage', models.IntegerField()),
                ('picture', models.URLField()),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='UserPlante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('rappel', models.BooleanField()),
                ('plantes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantes.plante')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rappel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailDate', models.DateField()),
                ('userplante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SaveUserPlante', to='plantes.userplante')),
            ],
        ),
    ]
