# Generated by Django 4.1.7 on 2023-03-25 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantes', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userplante',
            old_name='plantes',
            new_name='plante',
        ),
    ]
