# Generated by Django 4.1.7 on 2023-04-02 01:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantes', '0004_rename_plantes_userplante_plante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rappel',
            name='emailDate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
