# Generated by Django 4.1.7 on 2023-04-02 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantes', '0005_alter_rappel_emaildate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplante',
            name='date_futur',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='rappel',
            name='emailDate',
            field=models.DateField(),
        ),
    ]
