# Generated by Django 4.1.7 on 2023-04-25 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantes', '0007_alter_rappel_emaildate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplante',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
